# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Bearing load builder', kernelModule='Bearing_load', kernelFunction='bearing_load', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgTextField(p='DialogBox', fieldType='String', ncols=45, labelText='Load name', keyword='loadName', default='Bearing')
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Step:', keyword='stepName', default='', comboType='MDB', repository='steps', rootText='Model:', rootKeyword='modelName', layout='HORIZONTAL')
RsgTextField(p='DialogBox', fieldType='String', ncols=40, labelText='Surface set name', keyword='setName', default='')
RsgPickButton(p='DialogBox', text='Cylindrical CSYS', keyword='cylCsys', prompt='Pick a cylindrical CSYS', entitiesToPick='MDB_GEOMETRY|DATUM_CSYS', numberToPick='ONE')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Radial force', keyword='radialForce', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Face radius', keyword='faceRadius', default='')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Face height', keyword='faceHeight', default='')
dialogBox.show()