# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Copy layup', kernelModule='Copy_layup', kernelFunction='copy_layup', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Part:', keyword='partName1', default='', comboType='MDB', repository='parts', rootText='From Model:', rootKeyword='modelName1', layout='HORIZONTAL')
RsgComboBox(name='ComboBox_2', p='DialogBox', text='Part:', keyword='partName2', default='', comboType='MDB', repository='parts', rootText='To Model:', rootKeyword='modelName2', layout='HORIZONTAL')
dialogBox.show()