# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
from kernelAccess import session, mdb

def getCurrentModel():
    """
    Ritorna una stringa contenente il nome del modello attualmente
    attivo nel viewport
    """
    vpName = session.currentViewportName
    return str(session.sessionState[vpName]['modelName'])

parti = mdb.models[getCurrentModel()].parts.keys()

execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Instance replace custom', kernelModule='Instance_replace_custom', kernelFunction='instance_replace_custom', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgPickButton(p='DialogBox', text='Instance to replace', keyword='oldInstance', prompt='Pick instance to replace', entitiesToPick='MDB_GEOMETRY|INSTANCES', numberToPick='ONE')
RsgComboBox(name='ComboBox_2', p='DialogBox', text='Select new part:', keyword='newPart', default=parti[0], comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
for ii in parti:
    RsgListItem(p='ComboBox_2', text=ii)
RsgCheckButton(p='DialogBox', text='Infer tangent faces', keyword='tangentSearchFlag', default=True)
dialogBox.show()