# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='3D element layer', kernelModule='Element_layer_3D', kernelFunction='element_layer_3D', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgPickButton(p='DialogBox', text='Select faces:', keyword='faces', prompt='Select faces', entitiesToPick='MDB_GEOMETRY|FACES', numberToPick='MANY')
RsgTextField(p='DialogBox', fieldType='Integer', ncols=12, labelText='Number of layers:', keyword='nLayers', default='')
dialogBox.show()