# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Symmetric hex mesh', kernelModule='HexSymMesh', kernelFunction='symHexMesh', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgPickButton(p='DialogBox', text='Mirror faces', keyword='mirrorFaces', prompt='Pick symmetry faces', entitiesToPick='MDB_GEOMETRY|FACES', numberToPick='MANY')
RsgCheckButton(p='DialogBox', text='Associate to geometry', keyword='assocFlag', default=True)
dialogBox.show()