# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Lag screw wizard', kernelModule='Lag_screw_wizard', kernelFunction='lag_screw_wizard', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgPickButton(p='DialogBox', text='Point 1', keyword='point1', prompt='Pick the first point (head)', entitiesToPick='MDB_GEOMETRY|DATUM_POINTS', numberToPick='ONE')
RsgPickButton(p='DialogBox', text='Point 2', keyword='point2', prompt='Pick the second point shank-thread transition)', entitiesToPick='MDB_GEOMETRY|DATUM_POINTS', numberToPick='ONE')
RsgPickButton(p='DialogBox', text='Point 3', keyword='point3', prompt='Pick the third point (end)', entitiesToPick='MDB_GEOMETRY|DATUM_POINTS', numberToPick='ONE')
RsgTextField(p='DialogBox', fieldType='Float', ncols=12, labelText='Metric:', keyword='metric', default='6')
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Class:', keyword='boltClass', default='8.8', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='4.8')
RsgListItem(p='ComboBox_1', text='5.8')
RsgListItem(p='ComboBox_1', text='6.8')
RsgListItem(p='ComboBox_1', text='8.8')
RsgListItem(p='ComboBox_1', text='10.9')
RsgListItem(p='ComboBox_1', text='12.9')
RsgCheckButton(p='DialogBox', text='Automatic contact search', keyword='contactFlag', default=True)
RsgCheckButton(p='DialogBox', text='Automatic tie search', keyword='tieFlag', default=True)
RsgCheckButton(p='DialogBox', text='Use adjust length', keyword='adjustLengthFlag', default=True)
dialogBox.show()