# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog orient.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
modelli = [ii for ii in mdb.models.keys()]
if not modelli:
    modelli = ['']
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Title', kernelModule='Beam_auto_orient', kernelFunction='beam_auto_orient', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Model:', keyword='modelName', default=modelli[0], comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
for modello in modelli:
    RsgListItem(p='ComboBox_1', text=modello)
dialogBox.show()