# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Predefined field output', kernelModule='Predefined_output', kernelFunction='predefined_output', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Select case:', keyword='caso', default='Standard', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='Standard')
RsgListItem(p='ComboBox_1', text='Composite')
RsgListItem(p='ComboBox_1', text='Contact')
RsgListItem(p='ComboBox_1', text='Plastic')
RsgCheckButton(p='DialogBox', text='Delete existing fields', keyword='deleteFlag', default=True)
RsgCheckButton(p='DialogBox', text='Delete history outputs', keyword='historyFlag', default=True)
dialogBox.show()