# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
import glob
jobs = glob.glob('*.lck')
if not jobs:
    jobs = ['']
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Job killer', kernelModule='Job_killer', kernelFunction='job_killer', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Job to kill:', keyword='jobName', default=jobs[0].replace('.lck',''), comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
for ii in jobs:
    RsgListItem(p='ComboBox_1', text=ii.replace('.lck',''))
dialogBox.show()