# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
from kernelAccess import session, mdb

def getCurrentModel():
    """
    Ritorna una stringa contenente il nome del modello attualmente
    attivo nel viewport
    """
    vpName = session.currentViewportName
    return str(session.sessionState[vpName]['modelName'])

sezioni = mdb.models[getCurrentModel()].sections.keys()
if not sezioni:
    sezioni = ['']

execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Assign multiple secitons', kernelModule='Assign_sections', kernelFunction='assingn_sections', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgComboBox(name='ComboBox_1', p='DialogBox', text='Select section:', keyword='sectionName', default=sezioni[0], comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
for ii in sezioni:
    RsgListItem(p='ComboBox_1', text=ii)
RsgCheckButton(p='DialogBox', text='Overwrite previously assigned sections', keyword='overwriteFlag', default=False)
RsgPickButton(p='DialogBox', text='Select parts:', keyword='instList', prompt='Select parts', entitiesToPick='MDB_GEOMETRY|INSTANCES', numberToPick='MANY')
dialogBox.show()