# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='2D element layer', kernelModule='Element_layer_2D', kernelFunction='element_layer_2d', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgPickButton(p='DialogBox', text='Select edges', keyword='edges', prompt='Select edges', entitiesToPick='MDB_GEOMETRY|EDGES', numberToPick='MANY')
RsgTextField(p='DialogBox', fieldType='Integer', ncols=12, labelText='Layers:', keyword='nLayers', default='')
dialogBox.show()